apiVersion: scalingpolicy.kope.io/v1alpha1
kind: ScalingPolicy
metadata:
  name: fluentbit-gke-scaling-policy
  namespace: kube-system
spec:
  containers:
    - name: fluentbit-gke
      resources:
        requests:
          - resource: cpu
            base: 30m
          - resource: memory
            base: 50Mi
        limits:
          - resource: memory
            base: 250Mi