apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  selector:
    matchLabels:
      app: producer
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
        tier: backend
        track: stable
    spec:
      containers:
      - name: producer
        image: gcr.io/fiuba-rpl/rpl-2.0:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "local,producer,development"
        - name: QUEUE_SERVICE_HOST
          value: queue
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          httpGet:
            path: /api/health
            port: 8080
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 8080
        resources:
          limits:
            memory: 512Mi