apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
        tier: backend
        track: stable
    spec:
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      containers:
      - name: rabbitmq
        image: deadtrickster/rabbitmq_prometheus:latest
        ports:
          - containerPort: 15671
          - containerPort: 15672
          - containerPort: 5671
          - containerPort: 5672
          - containerPort: 9419
        resources:
          requests:
            cpu: 50m
            memory: 300Mi
