apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: rabbitmq
        image: deadtrickster/rabbitmq_prometheus:latest
        ports:
          - containerPort: 15671
          - containerPort: 15672
          - containerPort: 5671
          - containerPort: 5672
          - containerPort: 9419
        resources:
          limits:
            memory: 512Mi
