apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  ports:
  - port: 15671
    targetPort: 15671
    name: tcp-15671
    nodePort: 30000
  - port: 15672
    targetPort: 15672
    name: tcp-15672
  - port: 5671
    targetPort: 5671
    name: tcp-5671
  - port: 5672
    targetPort: 5672
    name: tcp-5672
  - port: 9419
    targetPort: 9419
    name: tcp-9419
  type: NodePort
  selector:
    app: queue